### ISSUE TITLE
Laravel 5.1 Removed createMatcher method

### ISSUE THREAD

**Issue by mean-cj** [Marwelln/basset#1]
Hello

Thank you for your dev, I'm found fatal error.

FatalErrorException in BassetServiceProvider.php line 85:
Call to undefined method Illuminate\View\Compilers\BladeCompiler::createMatcher()
## 

The createMatcher, createOpenMatcher, and createPlainMatcher methods have been removed from the Blade compiler. Use the new directive method to create custom directives for Blade in Laravel 5.1. Consult the extending blade documentation for more information.

Thanks
CJ

**Comment by Marwelln** [comment]
Feel free to create a pull request. I don't work with this anymore.
